
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

env:
  - TESTFOLDER=tools/metaMS_runGC
  - TESTFOLDER=tools/metaMS_plot

before_install:
 - sudo apt-get install -y python-virtualenv
 - virtualenv planemo-venv
 - . planemo-venv/bin/activate
 - pip install planemo==0.58.1
 - sudo apt-get install ghostscript
  
# @TODO: remove ASAP
# The issue: https://github.com/galaxyproject/planemo/issues/865
install:
  - for LINK in $(find ${TRAVIS_BUILD_DIR}/${TESTFOLDER}/test-data/ -type l -exec ls {} \;); do REALPATH=$(readlink -f $LINK); rm -f $LINK; cp $REALPATH $LINK; done
script:
 - planemo lint ${TRAVIS_BUILD_DIR}/${TESTFOLDER}
   # --conda_ensure_channels bioconda,workflow4metabolomics,conda-forge,default
 - planemo test --galaxy_branch release_18.05 --no_cache_galaxy ${TRAVIS_BUILD_DIR}/${TESTFOLDER}


